### ISSUE TITLE
Missing Data Files

### ISSUE THREAD

**Issue by weimingwill** [mtensor/neural_sketch#1]
Hi, I tried to run the program, but encoutered problem in loading data `data/DeepCoder_data/T2_A2_V512_L10_train.txt`. 

I downloaded deepcoder data from their github and the data format is `T=2_train.json`. May I know how can I transform it to the correct format? 

Thank you.

**Comment by mtensor** [comment]
I just added a zipped version of the data for the list domain to the repo. Let me know if that doesn't work or you have any more questions.

**Comment by weimingwill** [comment]
@mtensor  Thank you

**Comment by weimingwill** [comment]
Hi @mtensor , can you also provide `precomputed_data_files` for evaluation? e.g. `prelim_val_data_new.p`, `prelim_val_data.p`? Thank you.

**Comment by mtensor** [comment]
I added `T3_test_data_new.p` and `T44_test_new.p` to the data folder on master, which I believe are the precomputed data files for evaluation of the list domain used in Fig 2.
