### ISSUE TITLE
Where exactly is "algolispPrimitives" defined? 

### ISSUE THREAD

**Issue by Sammed98** [mtensor/neural_sketch#2]
There is no package by the name of algolispPrimitives and there is no class within the code. Could you help me with this?
For grammar, there is a package of the same name. Have you used that one or something else?

**Comment by shini-tm** [comment]
some folders are linked to other repositories, i think the algolisp stuff is in https://github.com/mtensor/program_synthesis/tree/45aa4a019094e67a1beed21c3db8ca5608bd6605

**Comment by Sammed98** [comment]
I have seen that. I have downloaded the corresponding files and placed them appropriately. And even if you search the terms within the repository you don't find it.

**Comment by mtensor** [comment]
I used the `working-mnye` branch for experiments, which links to necessary submodules. You can find algolispPrimitives.py in the `ec` directory: https://github.com/ellisk42/ec/blob/8360ff34834a42bb94af8e43cb13fe9f00bdca4e/algolispPrimitives.py
