### ISSUE TITLE
Missing "basegrammar.p" file.

### ISSUE THREAD

**Issue by Sammed98** [mtensor/neural_sketch#3]
Is there some code to generate a basegrammar.p file? There is a comment FixThis near the basegrammar variable. Can you help me with this?

**Comment by mtensor** [comment]
If you are looking at the Algolisp domain, a "naive" base grammar can be produced by the following line: https://github.com/mtensor/neural_sketch/blob/cf4f889f6f8e2c780e3916064c54f41cee6a43f2/data_src/makeAlgolispData.py#L37
A "naive" base grammar will be a grammar with uniform production probabilities for each primitive in the PCFG.

To fit the production probabilities to the training data, you can use the function `reweightbasegrammar`, using the naive base grammar as the input:
https://github.com/mtensor/neural_sketch/blob/cf4f889f6f8e2c780e3916064c54f41cee6a43f2/data_src/makeAlgolispData.py#L342

(essentially, run the lines of code after the `assert False` on line 340)

**Comment by Sammed98** [comment]
It worked. I placed 
```
with open('basegrammar.p', 'rb') as file:
		basegrammar = pickle.load(file)
```
just before the for i in c loop and the training started.
